### ISSUE TITLE
2.0.0-beta3 | AOVs missing

### ISSUE THREAD

**Issue by chittyren** [anderslanglands/alShaders2#32] opened 2018-05-08 22:25 UTC
I'm having trouble getting the latest beta release working for Maya 2018.2.  The cryptomatte AOVs aren't showing up in the "Available AOVs" list.  

Here are my specs:
> Windows 10 Pro (build 16299)
> Maya 2018.2 / mtoa 2.1.0.1 (Arnold Core 5.0.2.1) (mtoa is installed locally)
> 2.0.0-beta3 release 

Here is what I've tried:
* Followed the instructions listed on the [mtoa docs](https://support.solidangle.com/display/A5AFMUG/Cryptomatte).  Copying contents of *bin/* folder into *mtoadeploy/2018/shaders* folder.
  *  Tried dumping them into the *mtoadeploy/2018/bin/* folder instead
* Created a mod file to append folders.  Env variables were taken from [this video](https://youtu.be/eJ85CXPk7uU?t=8m17s).  Mod file code below...
```
+ cryptomatte any C:/path/to/alShaders-win-2.0.0b3-ai5.0.1.0
ARNOLD_PLUGIN_PATH +:= bin
MTOA_TEMPLATES_PATH +:= ae
```
> Verified the paths were appended to the env variables when I print them in Maya.  Output below
```
MTOA_TEMPLATES_PATH = ;C:/path/to/alShaders-win-2.0.0b3-ai5.0.1.0/ae/
ARNOLD_PLUGIN_PATH = ;C:/path/to/alShaders-win-2.0.0b3-ai5.0.1.0;C:/solidangle/mtoadeploy/2018/shaders;C:/solidangle/mtoadeploy/2018/procedurals
```
> NOTE: If I copy the contents from the Beta2 release's *bin/* to the *mtoadeploy/2018/shaders* it works!  However the mod file method doesn't.  Not sure why.

Is there anything I'm missing with installation of Beta3 release?  Any advice or assistance would be greatly appreciated!  Let me know if there is any additional information I can provide.

Thanks in advance!

**Comment by jonahfriedman** [comment] 2018-05-10 16:19
I don't really know, but a piece of info that might help you: The AOVs are specified by the .mtd file, so I would look to that to see what's wrong. Maybe you have an old one also installed somewhere? 

> Is there anything I'm missing with installation of Beta3 release?

There's nothing special about Beta3 as far as installation is concerned.

**Comment by jonahfriedman** [comment] 2018-05-17 15:57
Closing this - hope you got it figured out.

**Comment by jonahfriedman** [comment] 2018-05-17 20:07
Oh, and make sure you have the [Visual Studio 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed.

**Comment by chittyren** [comment] 2018-05-18 00:51
Hey Jonah,
Still no luck with any of the following actions.

>Oh, and make sure you have the Visual Studio 2015 Redistributable installed.

I fixed my mod file per your notes.  So the /bin is apart of the cryptomatte path.

I've tried Visual Studio 2015 (x64 & x86), even downloaded Visual Studio 2017 per the link on the release notes.  Did this with all the tests I've done before, and the AOVs still don't show up.

I'm hesitant suggesting to compile the source on my end, as I've never done it before.  And would not want to bug you with learning how to do that.  I can use Beta2 in the meantime until something else breaks.  As Schmucker noted, it works as expected.

**Comment by jonahfriedman** [comment] 2018-05-18 14:32
Does the shader appear in Maya at all, i.,e. can you create a Cryptomatte shader?

**Comment by chittyren** [comment] 2018-05-18 23:55
No, I don't see the cryptomatte node in the hypershade using Beta3.  I can with Beta2 though.

**Comment by jonahfriedman** [comment] 2018-06-01 15:50
Just a note- the fact that the shader can't be created in the hyperahde probably means it doesn't load at all, and doesn't have to do with the metadata. The 2017 redistributable is a possible reason why, though you say you've already installed that. You can try beta 4, but that requires the same redistributable, so it's unlikely to be different.

**Comment by chittyren** [comment] 2018-06-21 22:22
Hey Jonah,
Any further information on getting a fix for this issue?  I'm still struggling to figure out why Maya isn't loading the plugin.  I've down a complete reinstall of Visual C++ Distros including 2017 (found out x64 systems need both the x86 and x64 installed).

**Comment by chittyren** [comment] 2018-06-21 22:45
@jonahfriedman - Any updated information on a potential fix for this issue?  I've tried beta4 and as you predicted it doesn't work.  I'm still struggling to figure out why the plugin isn't loading.  I've reinstalled all the relevant Microsoft Visual C++ Distros for Maya 2018 as well as the Visual C++ 2017 Distros to fix an unrelated issue and still had no luck with beta3 and up.

**Comment by anderslanglands** [comment] 2018-06-22 01:45
Can you try setting your startup log verbosity to 2 and add the contents on
your output window on maya startup here?
https://support.solidangle.com/display/arnsupp/2014/06/26/%5BMtoA%5D+Setting+the+startup+log+verbosity

**Comment by baiking** [comment] 2018-06-22 02:50
I've got the same problem,beta2 work for mtoa 2.1.x.x,  beta3/4 only work for mtoa 3.0.x
The log say:
cryptomate.dll was compiled against not-compatible Arnold 5.1.0.1

**Comment by chittyren** [comment] 2018-06-22 14:36
@anderslanglands - Here is the full log from startup.  Looks to be the same issue as baiking reported.

```
00:00:00   878MB         | log started Fri Jun 22 10:28:13 2018
00:00:00   878MB         | Arnold 5.0.2.1 [0c7988c0] windows icc-17.0.2 oiio-1.7.17 osl-1.9.0 vdb-4.0.0 clm-1.0.3.513 rlm-12.2.2 2017/11/17 14:49:26
00:00:00   878MB         | running on cgi11, pid=10248
00:00:00   878MB         |  2 x Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz (20 cores, 40 logical) with 130987MB
00:00:00   878MB         |  Windows 8 Professional (version 6.2, build 9200)
00:00:00   878MB         |  soft limit for open files raised from 512 to 2048
00:00:00   878MB         |  
00:00:00   878MB         | loading plugins from R:/resources/_ns_tools/maya/plugins/cryptomatte/2.0.0b4/win/bin ...
00:00:00   878MB WARNING |  cryptomatte.dll was compiled against non-compatible Arnold 5.1.0.1
00:00:00   878MB         | no plugins loaded
00:00:00   880MB         | loading plugins from R:/resources/_ns_tools/maya/plugins/cryptomatte/2.0.0b4/win/bin ...
00:00:00   880MB WARNING |  cryptomatte.dll was compiled against non-compatible Arnold 5.1.0.1
00:00:00   880MB         | loading plugins from R:/resources/_ns_tools/maya/plugins/mtoa/2.1.0.1/2018/win/shaders ...
00:00:00   882MB         | loading plugins from R:/resources/_ns_tools/maya/plugins/mtoa/2.1.0.1/2018/win/procedurals ...
00:00:00   882MB         | loaded 123 plugins from 10 lib(s) in 0:00.05
00:00:00   888MB         | loading plugin: C:/Program Files/Autodesk/bifrost/1.5.0/Arnold-5.0.0.0/bin/bifrost_procedural_0_1.dll ...
00:00:00   888MB         | loaded 5 plugins from 1 lib(s) in 0:00.00
00:00:00   889MB         | Successfully imported python module 'arnold'
00:00:00   889MB         | Successfully imported python module 'mtoa'
00:00:01   891MB         |  
00:00:01   891MB         | releasing resources
00:00:01   890MB         | Arnold shutdown
```

**Comment by anderslanglands** [comment] 2018-06-26 04:58
Huh. I changed this a while ago. Let me check.

**Comment by 3b33** [comment] 2018-07-26 12:24
Not getting the AOVs either with beta 4. Maya 2018.2, Arnold 2.0.2.1, win10. Any news on this?

**Comment by jonahfriedman** [comment] 2018-07-27 14:48
We're moving the repo to [Psyop/CryptomatteArnold](https://github.com/Psyop/CryptomatteArnold) very soon, this issue should be fixed. OS X should be up soon, at which time we'll replace this repo's readme.md with a note that it has moved.

"AOVS not showing up" is better described as the shader not loading, and the reason for this was that that Cryptomatte was built with a newer version of Arnold for the version you are using. It is now built against 5.0.1.0, and with Visual Studio 2015 (and not 2017), so it should be fixed. 

If the issue isn't solved, please open an issue on the new repo.

**Closed by jonahfriedman** 2018-07-27 14:48 UTC

**Comment by chittyren** [comment] 2018-08-01 20:01
Just wanted to follow up.  Updating to the latest release from the CryptomatteArnold repo fixed this issue for us!  Thank you @jonahfriedman !
