### ISSUE TITLE
Crash with paralell init and multiple Cryptomatte shaders in scene

### ISSUE THREAD

**Issue by samhodge** [anderslanglands/alShaders2#30] opened 2018-05-07 06:10 UTC
Please see:

https://gist.github.com/samhodge/86173d3797f3ad77fa60e93fd4990a94

crash is 

`****
* Arnold 5.1.0.X linux clang-5.0.0 oiio-1.7.17 osl-1.9.0 vdb-4.0.0 clm-1.0.3.513 rlm-12.2.2 2018/05/XX XX:XX:XX
00:00:00    61MB         |   Cryptomatte manifest created - 0.000000 seconds
00:00:00    61MB         |   Cryptomatte manifest created - 0.000000 seconds
* CRASHED in AiArrayGetStrFunc at 00:00:00
* signal caught: SIGSEGV -- Invalid memory reference
*
* backtrace:
*  0 0x00007f961aea17e2 [libai.so       ]                                                                              
*  1 0x00000030f763265f [libc.so.6      ]                                                                              
>> 2 0x00007f961a82135b [libai.so       ] AiArrayGetStrFunc                                                            
*  3 0x00007f961a82135b [libai.so       ] AiArrayGetStrFunc                                                            
*  4 0x00007f9604bfa998 [cryptomatte.so ] CryptomatteData::setup_all(AtString, AtString, AtString, AtArray*, AtArray*)
*  5 0x00007f9604bf6f23 [cryptomatte.so ]                                                                              [cryptomatte_shader.cpp:0]
*  6 0x00007f961ae040bb [libai.so       ]                                                                              
*  7 0x00007f961ae0fc7b [libai.so       ]                                                                              
*  8 0x00007f961aea4d0d [libai.so       ]                                                                              
*  9 0x00000030f7e07aa0 [libpthread.so.0]                                                                              [pthread_create.c      :0]
* 10 0x00000030f76e8aac [libc.so.6      ] clone                                                                        
*
* loaded modules:
*    0x00007f961a5b6000  libai.so
*    0x00000030f7600000  libc.so.6
*    0x00007f9604b62000  cryptomatte.so
*    0x00000030f7e00000  libpthread.so.0
*
* memory: VM 78323 MB, RSS 61 MB, 0 page faults
****
Segmentation fault`

Will not happen everytime indicating it is a concurrency issue.

**Comment by jonahfriedman** [comment] 2018-05-07 14:57
Thanks, I have reproduced the issue. 

I notice that your scene contains multiple Cryptomatte shaders, and they are not being used as AOV shaders. If i get rid of them all except one, and plug it into only AOV shaders, it works. This isn't quite the intended use case - Is there a reason you're using it this way? 

It probably is possible to fix the race condition.

**Comment by jonahfriedman** [comment] 2018-05-07 15:06
Furthermore it's caused by having more than one Cryptomatte in the scene at all, which can happen by accident in a lot of ways, so it does need fixing.

**Comment by jonahfriedman** [comment] 2018-05-07 21:33
This has been fixed and will be in the next release.

**Closed by jonahfriedman** 2018-05-07 21:33 UTC
Labels: bug
